{% set name = "sphinx-material" %}
{% set dunder_name = name.replace("-", "_") %}
{% set version = "0.0.35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ dunder_name }}/{{ dunder_name }}-{{ version }}.tar.gz
  sha256: 27f0f1084aa0201b43879aef24a0521b78dc8df4942b003a4e7d79ab11515852

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4
  run:
    - beautifulsoup4
    - css-html-js-minify
    - lxml
    - python >=3.6,<4
    - python-slugify
    - setuptools
    - sphinx >=2.0

test:
  imports:
    - sphinx_material

about:
  home: https://github.com/bashtage/sphinx-material
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Material sphinx theme
  doc_url: https://pypi.org/project/sphinx-material/#description
  dev_url: https://github.com/bashtage/sphinx-material

extra:
  recipe-maintainers:
    - FaustinCarter
    - mxr-conda
    - ndmaxar
    - oblute
    - rluria14
    - moorepants
